spring:
  application:
    name: axi-S3master
  cloud:
    aws:
      s3:
        endpoint: http://localhost:9000
        region: us-east-1
        credentials:
          access-key: minioadmin
          secret-key: minioadmin

server:
  port: 8081
